<template>
  <v-app>
    <HeaderMenu/>
    
    <div class="centering">
      <div>
        <h1 class="title">【GAN散歩】ジェネラティブな生田の潜在空間を探索したい</h1>
        <p class="sub-title">2022/03</p>
        <div class="wrap-image">
          <div class="image">
            <v-img
              alt="FTD-BOX"
              src="../../../assets/work/work-detail/gan-sanpo-ikuta.png"
              width="480"
            />
          </div>
        </div>
        <p class="text-left">
          I took a walk in the town "Ikuta" generated by GAN (Generative Adversarial Network).
        </p>
        <p class="text-left">
          ジモトぶらぶらマガジン「サンポー」にて記事を書かせていただきました。
          GAN（敵対的生成ネットワーク）で生成した川崎市多摩区の生田を散歩するという謎文章です。
          でも好きな町です。
        </p>
        <p class="text-left">
          <ul>
            <li><a class="link" href="https://sanpoo.jp/article/ikuta-gan-sanpo/" target="_blank" rel="noopener">【GAN散歩】ジェネラティブな生田の潜在空間を探索したい / サンポー</a><br/></li>
            <li><a class="link" href="https://hahaeatora.hateblo.jp/entry/2022/03/25/120000" target="_blank" rel="noopener">Webマガジン「サンポー」にてGAN散歩（ジェネラティブ生田）の記事を書きました / ダークサイドにようこそ! </a><br/></li>
          </ul>
        </p>
      </div>
    </div>
    <AppFooter/>
  </v-app>
</template>

<style lang="scss" scoped>
@import "../../../styles/common/centering.scss";
@import "../../../styles/common/wrap-image.scss";
.link {
  color: gray;
}
</style>

<script>
import HeaderMenu from '@/components/HeaderMenu.vue';
import AppFooter from '@/components/AppFooter.vue'

export default {
  name: 'App',

  components: {
    HeaderMenu,
    AppFooter,
  },

  data: () => ({
    //
  }),
};
</script>