<template>
  <v-app>
    <HeaderMenu/>
    
    <div class="centering">
      <div>
        <h1 class="title">GAN散歩</h1>
        <p class="sub-title">2022/03-10</p>
        <div class="wrap-image">
          <div class="image">
            <v-img
              alt="FTD-BOX"
              src="../../../assets/work/work-detail/gan-sanpos.jpg"
              width="480"
            />
          </div>
        </div>
        <p class="text-left">
          “GAN散歩” is a series of articles about walking in an imaginary town generated by GAN (Generative Adversarial Network). 
          There are many examples of GAN learning about landscapes. 
          However, the fact that this article was published in a non-technical web media about walking is also very significant to me.
        </p>
        <p class="text-left">
          ジモトぶらぶらマガジン「サンポー」にて、 
          GAN（敵対的生成ネットワーク）で生成した実在しない街を散歩するという記事を書いています。
          こちらのページは概要のみ紹介しているので、ぜひ記事の方もご覧ください。
        </p>
        <p class="text-left">
          <ul>
            <li><a class="link" href="https://sanpoo.jp/article/ikuta-gan-sanpo/" target="_blank" rel="noopener">【GAN散歩】ジェネラティブな生田の潜在空間を探索したい / サンポー</a><br/></li>
            <li><a class="link" href="https://sanpoo.jp/article/marumiya-gan-sanpo/" target="_blank" rel="noopener">【GAN散歩】好きな街を混ぜる / サンポー</a><br/></li>
            <li><a class="link" href="https://sanpoo.jp/article/inu-gan-sanpo/" target="_blank" rel="noopener">GANで生成した地元の散歩道を犬と歩く / サンポー</a><br/></li>
          </ul>
        </p>
        <h2 class="title">GAN散歩とは</h2>
        <div class="wrap-image">
          <div class="image">
            <v-img
              alt="FTD-BOX"
              src="../../../assets/work/work-detail/gan-somewhere.jpg"
              width="480"
            />
          </div>
        </div>
        <p class="text-left">
          GANとはGenerative Adversarial Network（敵対的生成ネットワーク）の略であり、
          生成モデルといわれる機械学習技術の1つです。
          よくある使い方として、
          大量の画像データを学習させることでそれらの特徴を踏まえた新しい画像を生成することができます。
          GAN散歩では、作者の思い入れのある散歩風景から画像データセットを作成し学習、
          どこか面影の残る実在しない街を生成してあーだこーだ言いながら散策します。
        </p>
        <div class="wrap-image">
          <div class="image">
            <v-img
              alt="FTD-BOX"
              src="../../../assets/work/work-detail/gan-sanpo-ikuta-blackbox.jpg"
              width="480"
            />
          </div>
        </div>
        <p class="text-left">
          例えばこちらの画像。神奈川県川崎市多摩区の生田を学習したAIにより生成された風景です。
          全体的にちょっとおかしいですが、特に気になるのは車道に置かれている謎の黒い立方体。
          位置的に危ないなあと変な気を回しますが、あちらの世界では道端の植木のように当たり前の存在なのかも。
        </p>
        <p class="text-left">
          昨今の画像生成AIはオンライン上の画像を無差別かつ大量に学習しています。
          それらに抗うわけでもなく、
          個人の趣味趣向に特化し誰の役にも立ちそうにないAIの生成物がお散歩メディアに掲載されている状況に、
          自分自身が満足しています。
        </p>
      </div>
    </div>
    <AppFooter/>
  </v-app>
</template>

<style lang="scss" scoped>
@import "../../../styles/common/centering.scss";
@import "../../../styles/common/wrap-image.scss";
.link {
  color: gray;
}
</style>

<script>
import HeaderMenu from '@/components/HeaderMenu.vue';
import AppFooter from '@/components/AppFooter.vue'

export default {
  name: 'App',

  components: {
    HeaderMenu,
    AppFooter,
  },

  data: () => ({
    //
  }),
};
</script>