<template>
  <v-app>
    <HeaderMenu/>
    
    <div class="centering">
      <div>
        <h1 class="title">GAN散歩 / サンポー</h1>
        <p class="sub-title">2022/03-04</p>
        <div class="wrap-image">
          <div class="image">
            <v-img
              alt="FTD-BOX"
              src="../../../assets/work/work-detail/gan-sanpo-ikuta.png"
              width="480"
            />
          </div>
        </div>
        <p class="text-left">
          This is a series of articles about walking around the town generated by GAN (Generative Adversarial Network).
        </p>
        <p class="text-left">
          ジモトぶらぶらマガジン「サンポー」にて、
          GAN（敵対的生成ネットワーク）で生成した実在しない街を散歩するという謎記事を書かせていただきました。
          どれも良い街です。
        </p>
        <p class="text-left">
          <ul>
            <li><a class="link" href="https://sanpoo.jp/article/ikuta-gan-sanpo/" target="_blank" rel="noopener">【GAN散歩】ジェネラティブな生田の潜在空間を探索したい / サンポー</a><br/></li>
            <li><a class="link" href="https://sanpoo.jp/article/marumiya-gan-sanpo/" target="_blank" rel="noopener">【GAN散歩】好きな街を混ぜる / サンポー</a><br/></li>
          </ul>
        </p>
      </div>
    </div>
    <AppFooter/>
  </v-app>
</template>

<style lang="scss" scoped>
@import "../../../styles/common/centering.scss";
@import "../../../styles/common/wrap-image.scss";
.link {
  color: gray;
}
</style>

<script>
import HeaderMenu from '@/components/HeaderMenu.vue';
import AppFooter from '@/components/AppFooter.vue'

export default {
  name: 'App',

  components: {
    HeaderMenu,
    AppFooter,
  },

  data: () => ({
    //
  }),
};
</script>